/**
 * Shared vocabulary for the release-signal monitor.
 *
 * Everything in `sources/` is deliberately source-agnostic: after the November
 * launch the same machinery can be pointed at any other unannounced title by
 * dropping new files into this directory.
 */

export type SourceType =
  | 'official'
  | 'storefront'
  | 'filing'
  | 'press'
  | 'community';

/** The public stance tag the timeline has always carried. */
export type Provenance = 'official' | 'unverified leak';

/** A raw, unparsed fetch result. Bodies are never persisted — only hashed. */
export interface Raw {
  url: string;
  body: string;
  contentType: string;
  fetchedAt: string;
}

/**
 * One observation from one source.
 *
 * `id` must be stable across polls for the *same* observation, so that a value
 * that later changes (a file size, an unlock time) re-fires the same candidate
 * instead of creating a second one. `fields` carries the values the runner
 * hashes to decide whether something actually moved.
 */
export interface Candidate {
  id: string;
  sourceId: string;
  sourceType: SourceType;
  provenance: Provenance;
  title: string;
  description: string;
  url: string;
  sourceLabel: string;
  /**
   * When the observable change happened.
   *
   * For a feed this is the item's publication date. For a listing diff it is
   * the moment the value was seen to move — a storefront naming a future date
   * is news today, and that future date belongs in `fields`, not here.
   */
  occurredAt: string;
  fields?: Record<string, string | number | null>;
}

export interface Source {
  id: string;
  label: string;
  sourceType: SourceType;
  provenance: Provenance;
  /** Trust prior used until the credibility ledger has enough history. */
  baseConfidence: number;
  /** Returns null when the source is not configured: skipped, never failed. */
  poll(): Promise<Raw | null>;
  parse(raw: Raw): Candidate[];
}

/** A candidate parked in the manual-approval queue. */
export interface PendingEntry extends Candidate {
  detectedAt: string;
  firstSeenAt: string;
  contentHash: string;
  timesSeen: number;
  confidence: number;
  corroborations: string[];
  /** Set when this observation restates an id that is already published. */
  supersedes?: string;
}

export interface RejectedEntry {
  id: string;
  sourceId: string;
  title: string;
  reason: string;
  rejectedAt: string;
}

/** An approved, publicly visible timeline entry. */
export interface TimelineEvent {
  id: string;
  /** Human-facing display date, derived from occurredAt at approval time. */
  date: string;
  occurredAt: string;
  detectedAt: string;
  title: string;
  description: string;
  source: string;
  sourceLabel: string;
  sourceId: string;
  sourceType: SourceType;
  provenance: Provenance;
  confidence: number;
  corroborations: string[];
  autoGenerated: boolean;
  badge?: string;
}

export interface EventsFile {
  version: number;
  updatedAt: string;
  events: TimelineEvent[];
}

export interface PendingFile {
  version: number;
  updatedAt: string;
  pending: PendingEntry[];
  rejected: RejectedEntry[];
}

export interface SourceSnapshot {
  lastPolledAt: string;
  status: 'ok' | 'error' | 'skipped' | 'unchanged';
  error?: string;
  /** Hash of the whole response body. Never the body itself. */
  bodyHash?: string;
  /** candidateId -> content hash. Hashes only, never payloads. */
  candidates: Record<string, string>;
  polls: number;
  errors: number;
}

export interface SnapshotFile {
  version: number;
  updatedAt: string;
  sources: Record<string, SourceSnapshot>;
}

export interface LedgerEntry {
  sourceId: string;
  sourceType: SourceType;
  candidates: number;
  approved: number;
  rejected: number;
  pending: number;
  corroborated: number;
  approvalRate: number | null;
  /** Blended trust score used to seed confidence on new candidates. */
  score: number;
  meanLeadHours: number | null;
  lastApprovedAt: string | null;
  /** Operational health, straight off the snapshot store. */
  polls: number;
  errors: number;
  uptime: number | null;
}

export interface LedgerFile {
  version: number;
  updatedAt: string;
  sources: Record<string, LedgerEntry>;
}
