import React from 'react';
import {
  events,
  formatTimestamp,
  isLatest,
  isUnverified,
  lastCheckedAt,
  updatedAt,
  type TimelineEvent,
} from '@/lib/events';

const sourceTypeLabel: Record<TimelineEvent['sourceType'], string> = {
  official: 'First party',
  storefront: 'Storefront',
  filing: 'Filing',
  press: 'Press',
  community: 'Community',
};

const Timeline = () => {
    return (
        <div className="w-full max-w-4xl mx-auto mt-16 p-6 bg-black/30 backdrop-blur-md rounded-2xl border border-white/10 shadow-2xl">
            <div className="mb-10 text-center">
                <p className="mb-3 text-xs font-mono uppercase tracking-[0.28em] text-yellow-300">
                    Updated {formatTimestamp(updatedAt)}
                </p>
                <h2 className="text-3xl font-bold text-white uppercase tracking-widest drop-shadow-lg">
                    Development & News Timeline
                </h2>
                <p className="mx-auto mt-4 max-w-2xl text-sm leading-relaxed text-gray-300">
                    Official updates and clearly labeled community reports. Rumors remain unconfirmed, and no leaked media is hosted here.
                </p>
                <p className="mx-auto mt-3 max-w-2xl text-xs font-mono text-gray-400">
                    Storefront and first-party listings are polled automatically; every
                    entry below was reviewed by a human before it was published.
                    Last checked {formatTimestamp(lastCheckedAt)}.
                </p>
            </div>
            <div className="relative border-l-4 border-yellow-500 ml-4 md:ml-10">
                {events.map((event) => {
                    const unverified = isUnverified(event);
                    const latest = isLatest(event);

                    return (
                    <div key={event.id} className="mb-10 ml-8 relative">
                        <div
                            className={`absolute -left-[45px] w-6 h-6 rounded-full border-4 border-black ${
                                latest
                                    ? unverified
                                        ? 'bg-white shadow-[0_0_22px_#f472b6] animate-pulse'
                                        : 'bg-white shadow-[0_0_22px_#facc15] animate-pulse'
                                    : 'bg-yellow-400'
                            }`}
                        />
                        <article
                            className={`p-6 rounded-lg border shadow-lg transition-all duration-300 hover:-translate-y-1 ${
                                unverified
                                    ? 'bg-pink-400/10 border-pink-300/50 hover:bg-pink-400/15'
                                    : latest
                                      ? 'bg-yellow-400/15 border-yellow-300/70 hover:bg-yellow-400/20'
                                    : 'bg-white/10 border-white/10 hover:bg-white/20'
                            }`}
                        >
                            <div className="mb-2 flex flex-wrap items-center gap-3">
                                <span className={`block text-sm font-mono uppercase tracking-wider ${
                                    unverified ? 'text-pink-300' : 'text-yellow-300'
                                }`}>
                                    {event.date}
                                </span>
                                {event.badge && (
                                    <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.16em] text-black ${
                                        unverified ? 'bg-pink-300' : 'bg-yellow-300'
                                    }`}>
                                        {event.badge}
                                    </span>
                                )}
                                <span className="rounded-full border border-white/25 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.16em] text-gray-200">
                                    {sourceTypeLabel[event.sourceType]}
                                </span>
                                {event.autoGenerated && (
                                    <span
                                        className="rounded-full border border-cyan-300/40 px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-cyan-200"
                                        title="Detected by the monitor, then reviewed and approved by a human."
                                    >
                                        auto-detected
                                    </span>
                                )}
                            </div>
                            <h3 className="text-xl font-bold text-white mb-2">{event.title}</h3>
                            <p className="text-gray-200 leading-relaxed">
                                {event.description}
                            </p>
                            {event.corroborations.length > 0 && (
                                <p className="mt-3 font-mono text-xs text-gray-400">
                                    Corroborated by {event.corroborations.length} other{' '}
                                    {event.corroborations.length === 1 ? 'entry' : 'entries'}.
                                </p>
                            )}
                            <a
                                className={`mt-4 inline-flex items-center gap-2 text-sm font-semibold transition-colors hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 ${
                                    unverified
                                        ? 'text-pink-300 focus-visible:outline-pink-300'
                                        : 'text-yellow-300 focus-visible:outline-yellow-300'
                                }`}
                                href={event.source}
                                target="_blank"
                                rel="noreferrer"
                            >
                                {event.sourceLabel}
                                <span aria-hidden="true">↗</span>
                            </a>
                        </article>
                    </div>
                    );
                })}
            </div>
            <p className="mt-2 text-center font-mono text-xs text-gray-500">
                Machine-readable feed:{' '}
                <a className="text-gray-400 underline hover:text-yellow-300" href="/api/events.json">
                    /api/events.json
                </a>
            </p>
        </div>
    );
};

export default Timeline;
