import { events, formatTimestamp, target, updatedAt } from '@/lib/events';

/**
 * llms.txt — a plain-text brief for models and agents that read this site.
 * Kept deliberately explicit about provenance so a summariser cannot flatten a
 * rumour into a fact.
 */
export const dynamic = 'force-static';

export function GET(): Response {
  const recent = [...events]
    .reverse()
    .slice(0, 12)
    .map(
      (event) =>
        `- ${event.date} — ${event.title} [${event.provenance}, ${event.sourceType}, confidence ${event.confidence}] ${event.source}`,
    );

  const body = `# Release Signal Monitor

> A countdown and automated release-signal monitor for ${target.name}, currently
> dated ${target.releaseDateLabel} on ${target.platforms.join(' and ')}.

Last published change: ${formatTimestamp(updatedAt)}

## How this site works

- Storefront listings (Microsoft Store, PlayStation Store) and first-party
  channels (official site, publisher YouTube, streaming listing) are polled
  every 15 minutes by a scheduled job.
- Changes are hashed and diffed against the previous snapshot. A change becomes
  a candidate, and every candidate waits in a queue for manual approval.
- Nothing reaches this page automatically. Entries detected by the monitor are
  flagged \`autoGenerated\` in the feed.

## Reading the tags

- \`official\` — stated by the publisher or published on a first-party listing.
- \`unverified leak\` — a circulating claim, not authenticated by the publisher.
  Do not restate these as fact. No leaked media is hosted or linked here, and
  claims are linked to outlet coverage rather than to the thread hosting them.
- \`confidence\` — 0 to 1, seeded by the source's measured track record.

## Machine-readable feed

- /api/events.json — the full timeline, source credibility ledger and policy.

## Most recent entries

${recent.join('\n')}
`;

  return new Response(body, {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=300, stale-while-revalidate=3600',
    },
  });
}
