import {
  events,
  lastCheckedAt,
  provenanceCopy,
  sourceHealth,
  target,
  updatedAt,
} from '@/lib/events';

/**
 * The public feed.
 *
 * Generated at build time and served as a static file, so it costs nothing to
 * host and cannot drift from what the page shows — both read the same JSON.
 */
export const dynamic = 'force-static';

export function GET(): Response {
  const body = {
    schema: 'https://countdown.shiben.dev/api/events.json',
    version: 1,
    generatedAt: new Date().toISOString(),
    updatedAt,
    lastCheckedAt,
    target: {
      name: target.name,
      releaseDate: target.releaseDate,
      platforms: target.platforms,
      preloadDate: target.preloadDate,
    },
    policy: {
      provenance: provenanceCopy,
      review:
        'Every entry is approved by a human before publication. Automatically detected entries are marked autoGenerated.',
      media:
        'No leaked media is hosted or linked. Claims are linked to outlet coverage rather than to the thread hosting the material.',
    },
    sources: sourceHealth,
    events,
  };

  return new Response(`${JSON.stringify(body, null, 2)}\n`, {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'public, max-age=300, stale-while-revalidate=3600',
      'access-control-allow-origin': '*',
    },
  });
}
