/**
 * The manual gate. Auto-generated candidates only reach the public timeline
 * through this script.
 *
 *   npm run queue                          list what is waiting
 *   npm run queue -- show <id>             full detail for one candidate
 *   npm run approve -- <id> [options]      publish it
 *   npm run queue -- reject <id> "why"     drop it, and never queue it again
 *
 * Approve options:
 *   --badge="Latest official update"   badge shown on the card
 *   --title="..."  --description="..." rewrite before publishing
 *   --provenance=official|"unverified leak"
 *   --confidence=0.8
 */
import { displayDate } from '../sources/util';
import type { PendingEntry, TimelineEvent } from '../sources/types';
import { readEvents, readPending, writeEvents, writePending } from './store';
import { notify } from './notify';

const argv = process.argv.slice(2);
const command = argv[0];

async function main(): Promise<void> {
  switch (command) {
    case 'list':
    case undefined:
      return list();
    case 'show':
      return show(argv[1]);
    case 'reject':
      return reject(argv[1], argv.slice(2).join(' '));
    case 'approve':
      return approve(argv[1], flags(argv.slice(2)));
    default:
      // Bare id is shorthand for approve.
      return approve(command, flags(argv.slice(1)));
  }
}

function list(): void {
  const { pending, rejected } = readPending();

  if (pending.length === 0) {
    console.log('queue is empty');
  }

  for (const entry of pending) {
    const flag = entry.supersedes ? ' ⟳ supersedes a published entry' : '';
    console.log(
      [
        `${entry.id}`,
        `  ${entry.title}`,
        `  ${entry.sourceType} · ${entry.provenance} · confidence ${entry.confidence}` +
          ` · seen ${entry.timesSeen}× · first ${entry.firstSeenAt.slice(0, 16)}${flag}`,
      ].join('\n'),
    );
  }

  console.log(
    `\n${pending.length} awaiting review · ${rejected.length} previously rejected`,
  );
}

function show(id: string | undefined): void {
  const entry = requirePending(id);
  console.log(JSON.stringify(entry, null, 2));
}

async function approve(
  id: string | undefined,
  options: Record<string, string>,
): Promise<void> {
  const entry = requirePending(id);
  const pendingFile = readPending();
  const eventsFile = readEvents();

  const occurredAt = options.occurredAt ?? entry.occurredAt;
  const provenance =
    (options.provenance as TimelineEvent['provenance']) ?? entry.provenance;

  const event: TimelineEvent = {
    id: entry.id,
    date: displayDate(occurredAt),
    occurredAt,
    detectedAt: entry.firstSeenAt,
    title: options.title ?? entry.title,
    description: options.description ?? entry.description,
    source: entry.url,
    sourceLabel: entry.sourceLabel,
    sourceId: entry.sourceId,
    sourceType: entry.sourceType,
    provenance,
    confidence: options.confidence
      ? Number(options.confidence)
      : entry.confidence,
    corroborations: crossReference(entry, eventsFile.events),
    autoGenerated: true,
    ...(options.badge
      ? { badge: options.badge }
      : provenance === 'unverified leak'
        ? { badge: 'Unverified leak' }
        : {}),
  };

  const existingIndex = eventsFile.events.findIndex(
    (candidate) => candidate.id === event.id,
  );

  if (existingIndex >= 0) {
    // A superseding observation replaces the entry it restates, so the timeline
    // never carries two versions of the same fact.
    eventsFile.events[existingIndex] = event;
    console.log(`updated published entry ${event.id}`);
  } else {
    eventsFile.events.push(event);
    console.log(`published ${event.id}`);
  }

  eventsFile.events.sort((a, b) => a.occurredAt.localeCompare(b.occurredAt));
  eventsFile.updatedAt = new Date().toISOString();
  writeEvents(eventsFile);

  pendingFile.pending = pendingFile.pending.filter(
    (candidate) => candidate.id !== entry.id,
  );
  pendingFile.updatedAt = eventsFile.updatedAt;
  writePending(pendingFile);

  if (process.env.NOTIFY_ON_APPROVE === '1') {
    await notify([event], { stage: 'published' });
  }
}

function reject(id: string | undefined, reason: string): void {
  const entry = requirePending(id);
  const pendingFile = readPending();

  pendingFile.rejected.unshift({
    id: entry.id,
    sourceId: entry.sourceId,
    title: entry.title,
    reason: reason || 'no reason given',
    rejectedAt: new Date().toISOString(),
  });
  pendingFile.pending = pendingFile.pending.filter(
    (candidate) => candidate.id !== entry.id,
  );
  pendingFile.updatedAt = new Date().toISOString();
  writePending(pendingFile);

  console.log(`rejected ${entry.id} — it will not be queued again`);
}

/**
 * Independent sources describing the same day corroborate each other. This is
 * what the credibility ledger later scores sources on.
 */
function crossReference(
  entry: PendingEntry,
  events: TimelineEvent[],
): string[] {
  const day = entry.occurredAt.slice(0, 10);
  const matches = events
    .filter(
      (event) =>
        event.id !== entry.id &&
        event.sourceId !== entry.sourceId &&
        event.occurredAt.slice(0, 10) === day,
    )
    .map((event) => event.id);

  return [...new Set([...entry.corroborations, ...matches])];
}

function requirePending(id: string | undefined): PendingEntry {
  if (!id) {
    console.error('missing candidate id — run `npm run queue` to list them');
    process.exit(1);
  }

  const { pending } = readPending();
  const exact = pending.find((entry) => entry.id === id);
  if (exact) return exact;

  const partial = pending.filter((entry) => entry.id.includes(id));
  if (partial.length === 1) return partial[0];
  if (partial.length > 1) {
    console.error(`"${id}" matches ${partial.length} candidates:`);
    for (const entry of partial) console.error(`  ${entry.id}`);
    process.exit(1);
  }

  console.error(`no pending candidate matching "${id}"`);
  process.exit(1);
}

function flags(args: string[]): Record<string, string> {
  const parsed: Record<string, string> = {};
  for (const arg of args) {
    const match = arg.match(/^--([a-zA-Z]+)=([\s\S]*)$/);
    if (match) parsed[match[1]] = match[2];
  }
  return parsed;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
