/**
 * The credibility ledger.
 *
 * Every source claims a confidence prior in its own file. This recomputes what
 * each one has actually earned — how often its candidates survived review, how
 * often another source independently backed it up, how far ahead of the event
 * it fired, and how reliably it responds at all.
 *
 * The resulting score feeds back into `poll.ts`, so a source that keeps
 * producing noise quietly loses confidence on everything it queues next.
 *
 *   npm run ledger              recompute and write data/ledger.json
 *   npm run ledger -- --print   recompute and print, write nothing
 */
import sources from '../sources/index';
import type { LedgerEntry, LedgerFile } from '../sources/types';
import {
  readEvents,
  readPending,
  readSnapshots,
  writeLedger,
} from './store';

/**
 * Shrinkage weight. With no history a source sits exactly on its declared
 * prior; it takes roughly this many reviewed candidates to move it meaningfully.
 */
const PRIOR_WEIGHT = 4;

function build(): LedgerFile {
  const events = readEvents().events;
  const { pending, rejected } = readPending();
  const snapshots = readSnapshots();

  const knownIds = new Set([
    ...sources.map((source) => source.id),
    ...events.map((event) => event.sourceId),
  ]);

  const entries: Record<string, LedgerEntry> = {};

  for (const sourceId of [...knownIds].sort()) {
    const source = sources.find((candidate) => candidate.id === sourceId);
    const snapshot = snapshots.sources[sourceId];

    const approvedEvents = events.filter((event) => event.sourceId === sourceId);
    const rejectedCount = rejected.filter(
      (entry) => entry.sourceId === sourceId,
    ).length;
    const pendingCount = pending.filter(
      (entry) => entry.sourceId === sourceId,
    ).length;

    const reviewed = approvedEvents.length + rejectedCount;
    const prior = source?.baseConfidence ?? 0.5;

    const leadHours = approvedEvents
      .filter((event) => event.autoGenerated)
      .map(
        (event) =>
          (Date.parse(event.detectedAt) - Date.parse(event.occurredAt)) /
          3_600_000,
      )
      .filter((hours) => Number.isFinite(hours));

    entries[sourceId] = {
      sourceId,
      sourceType: source?.sourceType ?? approvedEvents[0]?.sourceType ?? 'official',
      candidates: Object.keys(snapshot?.candidates ?? {}).length,
      approved: approvedEvents.length,
      rejected: rejectedCount,
      pending: pendingCount,
      corroborated: approvedEvents.filter(
        (event) => event.corroborations.length > 0,
      ).length,
      approvalRate: reviewed === 0 ? null : round(approvedEvents.length / reviewed),
      score: round(
        (approvedEvents.length + PRIOR_WEIGHT * prior) /
          (reviewed + PRIOR_WEIGHT),
      ),
      meanLeadHours:
        leadHours.length === 0
          ? null
          : round(leadHours.reduce((sum, hours) => sum + hours, 0) / leadHours.length, 1),
      lastApprovedAt:
        approvedEvents
          .map((event) => event.detectedAt)
          .sort()
          .at(-1) ?? null,
      polls: snapshot?.polls ?? 0,
      errors: snapshot?.errors ?? 0,
      uptime:
        snapshot && snapshot.polls > 0
          ? round((snapshot.polls - snapshot.errors) / snapshot.polls)
          : null,
    };
  }

  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    sources: entries,
  };
}

function round(value: number, places = 2): number {
  return Number(value.toFixed(places));
}

const ledger = build();

if (process.argv.includes('--print')) {
  for (const entry of Object.values(ledger.sources)) {
    console.log(
      `${entry.sourceId.padEnd(20)} score ${entry.score.toFixed(2)}` +
        ` · ${entry.approved} approved / ${entry.rejected} rejected / ${entry.pending} pending` +
        ` · uptime ${entry.uptime === null ? 'n/a' : `${Math.round(entry.uptime * 100)}%`}`,
    );
  }
} else {
  writeLedger(ledger);
  console.log(
    `ledger updated for ${Object.keys(ledger.sources).length} source(s)`,
  );
}
